_BASE_: "SOLOv2_cityscapes.yaml"
MODEL:
  WEIGHTS: "https://cloudstor.aarnet.edu.au/plus/s/chF3VKQT4RDoEqC/download"
  RESNETS:
    DEPTH: 50
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (18000,)
  MAX_ITER: 24000
