_BASE_: "Base-SOLOv2.yaml"
INPUT:
    MIN_SIZE_TRAIN: (800, 832, 864, 896, 928, 960, 992, 1024)
    MIN_SIZE_TRAIN_SAMPLING: "choice"
    MIN_SIZE_TEST: 1024
    MAX_SIZE_TRAIN: 2048
    MAX_SIZE_TEST: 2048